// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8xgsiN1TDyEtdPCYGr4Je_cfnpVZ475g',
    appId: '1:1054525125550:web:8823be07783b06a1360e3f',
    messagingSenderId: '1054525125550',
    projectId: 'bloomscape-b1507',
    authDomain: 'bloomscape-b1507.firebaseapp.com',
    databaseURL: 'https://bloomscape-b1507-default-rtdb.firebaseio.com',
    storageBucket: 'bloomscape-b1507.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs6zpPpNkwMTXQfAGfUqTkrBYWLCDvGNw',
    appId: '1:1054525125550:android:feb23d780b70391f360e3f',
    messagingSenderId: '1054525125550',
    projectId: 'bloomscape-b1507',
    databaseURL: 'https://bloomscape-b1507-default-rtdb.firebaseio.com',
    storageBucket: 'bloomscape-b1507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNJK3RgUyf-UhXoJ06sAQ7AWW_srVJiRo',
    appId: '1:1054525125550:ios:c913de718caad0b7360e3f',
    messagingSenderId: '1054525125550',
    projectId: 'bloomscape-b1507',
    databaseURL: 'https://bloomscape-b1507-default-rtdb.firebaseio.com',
    storageBucket: 'bloomscape-b1507.appspot.com',
    iosBundleId: 'com.example.bloomscape',
  );
}
